name: build

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.20.6, 19.9.0, 20.18.2, 21.7.3, 22.13.1, 23.6.1]

    steps:
    - name: Setup NodeJS
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Check out code
      uses: actions/checkout@v4

    - name: Install eslint
      run: npm install eslint@8.23.1 eslint-config-standard eslint-plugin-promise eslint-plugin-import eslint-plugin-node eslint-plugin-n@15.2.5 --save-dev

    - name: Install node-red-dev
      run: npm install -g node-red-dev

    - name: Build
      run: make build-all
