name: build

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.21.3, 16.20.2, 18.19.1, 20.11.1]

    steps:
    - name: Setup NodeJS
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Check out code
      uses: actions/checkout@v3

    - name: Install eslint
      run: npm install eslint@8.23.1 eslint-config-standard eslint-plugin-promise eslint-plugin-import eslint-plugin-node --save-dev

    - name: Install node-red-dev
      run: npm install -g node-red-dev

    - name: Build
      run: make build-all
